AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'test/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/**/*'
Metrics/LineLength:
  Max: 160
Metrics/PerceivedComplexity:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 100
Metrics/AbcSize:
  Max: 60
Metrics/ClassLength:
  Max: 300
Metrics/BlockLength:
  Max: 30
