AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'test/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
Metrics/LineLength:
  Max: 160
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Max: 400
Metrics/BlockLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
