language: ruby
sudo: required
addons:
  chrome: stable
rvm:
  - "2.6.5"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - "export DISPLAY=:99.0"
  - gem install bundler
services:
  - xvfb
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database disease_trakker_test;' -U postgres
  - yarn install --ignore-engines
  - bundle install
script:
  - bundle exec brakeman -qAzw1
  - bundle exec gemsurance
  - bundle exec rake test
  - bundle exec rake test:system
