version: "3"

services:
  sara-alert:
    image: "${SARA_ALERT_IMAGE}:development-test"
    ports:
      - "443:3000"
    env_file:
      - .env-prod
    restart: unless-stopped
    networks:
      - dt-net
    depends_on:
      - redis
      - postgres
    command: "bin/bundle exec rails s -u puma -p 3000 -b 'ssl://0.0.0.0?key=/app/disease-trakker/tls/puma.key&cert=/app/disease-trakker/tls/puma.crt'"
    volumes:
      - '~/tls:/app/disease-trakker/tls:ro'
  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - .env-prod
    restart: unless-stopped
    networks:
      - dt-net
  redis:
    image: "redis:rc-alpine"
    volumes:
      - 'redis:/data'
    command: redis-server
    restart: unless-stopped
    networks:
      - dt-net
  sidekiq:
    image: "${SARA_ALERT_IMAGE}:development-test"
    env_file:
      - .env-prod
    restart: unless-stopped
    networks:
      - dt-net
    command: "bin/bundle exec sidekiq -q default -q mailers"
    depends_on:
      - redis
      - sara-alert

volumes:
  redis:
  postgres:

networks:
  dt-net:
