version: "3"

services:
  sara-alert-enrollment:
    image: "${SARA_ALERT_IMAGE}:development-test"
    environment:
      - REDIS_URL=redis://redis-enrollment:6379/1
    env_file:
      - .env-prod-enrollment
    restart: unless-stopped
    networks:
      - dt-net-enrollment
    depends_on:
      - redis-enrollment
      - postgres-enrollment
    ports:
      - 3000:3000
    command: "bin/bundle exec rails s -u puma -p 3000 -b 'ssl://0.0.0.0?key=/app/disease-trakker/tls/puma.key&cert=/app/disease-trakker/tls/puma.crt'"
    volumes:
      - '~/tls:/app/disease-trakker/tls:ro'
  sara-alert-assessment:
      image: "${SARA_ALERT_IMAGE}:development-test"
      environment:
        - REDIS_URL=redis://redis-bridge:6379/1
      env_file:
        - .env-prod-assessment
      restart: unless-stopped
      networks:
        - dt-net-assessment
        - dt-net-bridge
      depends_on:
        - redis-bridge
        - postgres-assessment
      command: "bin/bundle exec rails s -u puma -p 3000 -b 'ssl://0.0.0.0?key=/app/disease-trakker/tls/puma.key&cert=/app/disease-trakker/tls/puma.crt'"
      volumes:
        - '~/tls:/app/disease-trakker/tls:ro'
  postgres-enrollment:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'postgres-enrollment:/var/lib/postgresql/data'
    env_file:
      - .env-prod-enrollment
    restart: unless-stopped
    networks:
      - dt-net-enrollment
  postgres-assessment:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'postgres-assessment:/var/lib/postgresql/data'
    env_file:
      - .env-prod-assessment
    restart: unless-stopped
    networks:
      - dt-net-assessment
  redis-enrollment:
    image: "redis:rc-alpine"
    volumes:
      - 'redis-enrollment:/data'
    command: redis-server
    restart: unless-stopped
    networks:
      - dt-net-enrollment
  redis-bridge:
    image: "redis:rc-alpine"
    volumes:
      - 'redis-bridge:/data'
    command: redis-server
    restart: unless-stopped
    networks:
      - dt-net-bridge
  sidekiq-enrollment:
    image: "${SARA_ALERT_IMAGE}:development-test"
    environment:
      - REDIS_URL=redis://redis-enrollment:6379/1
    env_file:
      - .env-prod-enrollment
    restart: unless-stopped
    networks:
      - dt-net-enrollment
    command: "bin/bundle exec sidekiq -q default -q mailers"
    depends_on:
      - redis-enrollment
      - sara-alert-enrollment
      - postgres-enrollment
  sidekiq-bridge-enrollment:
    image: "${SARA_ALERT_IMAGE}:development-test"
    environment:
      - REDIS_URL=redis://redis-bridge:6379/1
    env_file:
      - .env-prod-enrollment
    restart: unless-stopped
    networks:
      - dt-net-bridge
      - dt-net-enrollment
    command: "bin/bundle exec rake reports:receive_and_process_reports"
    depends_on:
      - redis-bridge
      - sara-alert-enrollment
      - postgres-enrollment
  sidekiq-bridge-assessment:
    image: "${SARA_ALERT_IMAGE}:development-test"
    environment:
      - REDIS_URL=redis://redis-bridge:6379/1
    env_file:
      - .env-prod-assessment
    restart: unless-stopped
    networks:
      - dt-net-bridge
      - dt-net-assessment
    command: "bin/bundle exec sidekiq -q default"
    depends_on:
      - redis-bridge
      - sara-alert-assessment
      - postgres-assessment
  nginx:
    image: nginx:latest
    volumes:
      - '~/tls/nginx.conf:/etc/nginx/nginx.conf:ro'
      - '~/tls/puma.key:/etc/nginx/puma.key:ro'
      - '~/tls/puma.crt:/etc/nginx/puma.crt:ro'
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    command: nginx -g 'daemon off;'
    depends_on:
      - sara-alert-assessment
      - sara-alert-enrollment
    networks:
      - dt-net-assessment
      - dt-net-enrollment

volumes:
  redis-enrollment:
  redis-bridge:
  postgres-assessment:
  postgres-enrollment:

networks:
  dt-net-enrollment:
  dt-net-assessment:
  dt-net-bridge:
