version: "3"

services:
  sara-alert-enrollment:
    image: ${SARA_ALERT_IMAGE}:latest
  sara-alert-assessment:
    image: ${SARA_ALERT_IMAGE}:latest
  sidekiq-enrollment:
    image: ${SARA_ALERT_IMAGE}:latest

