# The jurisdictions in this configuration file follow a hierarchical structure. A jurisdiction has a name,
# which is the key and two optional values, `symptoms` and `children`. `symptoms` defines the symptoms
# that the jurisdiction which they belong to would like to track, said jurisdiction will track the
# symptoms that it specifies ***IN ADDITION TO*** the symptoms specified by all of it's parent jurisdictions.
# A `symptom` will be identified by it's name, which is the key in the symptom object, a `value` and a `type`.
# The `value` of a symptom defines the threshold of the symptom, this is the value that is considered as
# symptomatic for the symptom which it is defining, only symptoms marked as 'required' will be considered when
# determining whether or not a patient is symptomatic. For float and integer symptoms, a reported symptom greater
# than or equal to the specified `value` wil be considered as symptomatic. Available values for the `type`
# field in a symptom are `FloatSymptom`, `IntegerSymptom`, or `BoolSymptom`. The `children` of a jurisdiction are
# nested jurisdictions that may have their own `symptoms` and/or `children`.
#
# Example Use:
#
# In the configuration below, the USA jurisdiction will have 3 symptoms, these symptoms will apply to the
# USA jurisdiction as well as ALL of it's nested children, meaning that all jurisdictions all the way down
# to the county-level jurisdictions will inherit these symptoms. State 1 has specified it's own symptoms which
# will be added to the symptoms that it inherited from its parent jurisdiction, these symptoms will be applied
# to State 1, and the children of State1 (County 1  and County 2). In other words, a monitoree in State 1,
# County 1 or County 2 will be asked about the symptoms Temperature, Cough, Difficulty Breathing and Vomit as
# part of their assessment, whereas a monitoree in State 2 or County 3 would only be asked about the symptoms
# Temperature, Cough and Difficulty Breathing as part of their assessment.
#
# ```
# 'USA':
#     symptoms:
#         'Temperature':
#             value: 100.4
#             type: 'FloatSymptom'
#         'Cough':
#             value: true
#             type: 'BoolSymptom'
#         'Difficulty Breathing':
#             value: true
#             type: 'BoolSymptom'
#     children:
#         'State 1':
#             symptoms:
#               'Vomit':
#                 value: true
#                 type: 'BoolSymptom'
#             children:
#                 'County 1':
#                 'County 2':
#         'State 2':
#             children:
#                 'County 3':

'USA':
    symptoms:
        # Key is the symptom name as it will appear to the user
        'Cough':
            # The value specified here is the threshold value for the particular symptom
            # values greater than or equal to this value are considered to be symptomatic
            # Useable values for type are [FloatSymptom, IntegerSymptom, or BoolSymptom]
            # The expected threshold value for bool_values should always be true
            value: true
            type: 'BoolSymptom'
            required: true
        'Difficulty Breathing':
            value: true
            type: 'BoolSymptom'
            required: true
        'Fever':
            value: true
            type: 'BoolSymptom'
            notes: 'Feeling feverish or have a measured temperature at or above 100.4°F/38°C'
            required: true
        'Used Fever A Reducer':
            value: true
            type: 'BoolSymptom'
            notes: 'In the past 24 hours, have you used any medicine that reduces fevers?'
            required: false
    # Jurisdictions follow a hierarchy, the hierarchy is defined by nesting jurisdictions
    # in the children: field
    children:
        'State 1':
            children:
                'County 1':
                'County 2':
        'State 2':
            children:
                'County 3':
                'County 4':
