'USA':
    symptoms: 
        # Key is the symptom name as it will appear to the user
        'Temperature': 
            # The value specified here is the threshold value for the particular symptom
            # values greater than or equal to this value are considered to be symptomatic
            # Useable values for type are [FloatSymptom, IntegerSymptom, or BoolSymptom]
            value: 101.4
            type: 'FloatSymptom'
        'Cough':
            # The expected threshold value for bool_values should always be true
            value: true
            type: 'BoolSymptom'
        'Difficulty Breathing':
            value: true
            type: 'BoolSymptom'
    # Jurisdictions follow a hierarchy, the hierarchy is defined by nesting jurisdictions
    # in the children: field
    children:
        'State 1':
            children:
                'County 1':
                'County 2':
        'State 2':
            children:
                'County 3':
                'County 4':
