# How many days an enrolled monitoree should be monitored
monitoring_period_days: <%= ENV["MONITORING_PERIOD_DAYS"] || 14 %>

# How many minutes in a reporting period (hint: 1440 mins for 24 hours)
reporting_period_minutes: <%= ENV["SARA_ALERT_REPORTING_PERIOD_MINUTES"] || 1440 %>

# Should Sara Alert send emails?
enable_email: <%= ENV["SARA_ALERT_ENABLE_EMAIL"] || true %>

# Should Sara Alert send SMS messages?
enable_sms: <%= ENV["SARA_ALERT_ENABLE_SMS"] || false %>

# Assessment Report Mode
report_mode: <%= ENV["SARA_ALERT_REPORT_MODE"] || false %>
