default: &default
  adapter: <%= ENV['DISEASE_TRAKKER_DATABASE_ADAPTER'].presence || 'postgresql' %>
  encoding: <%= ENV['DISEASE_TRAKKER_DATABASE_ENCODING'].presence || 'unicode' %>
  pool: <%= ENV['DISEASE_TRAKKER_DATABASE_POOL'].presence || ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  reconnect: <%= ENV['DISEASE_TRAKKER_DATABASE_RECONNECT'].presence || 'true' %>
  <%= ENV['DISEASE_TRAKKER_DATABASE_SOCKET'].presence ? 'socket: ' + ENV['DISEASE_TRAKKER_DATABASE_SOCKET'].presence : '' %>

development:
  <<: *default
  database: <%= ENV['DISEASE_TRAKKER_DATABASE_NAME'].presence || 'disease_trakker_development' %>

test:
  <<: *default
  database: <%= ENV['DISEASE_TRAKKER_DATABASE_NAME'].presence || 'disease_trakker_test' %>

production:
  <<: *default
  database: <%= ENV['DISEASE_TRAKKER_DATABASE_NAME'].presence || 'disease_trakker_production' %>
  username: <%= ENV['DISEASE_TRAKKER_DATABASE_USERNAME'].presence || 'disease_trakker' %>
  password: <%= ENV['DISEASE_TRAKKER_DATABASE_PASSWORD'] %>
  host: <%= ENV['DISEASE_TRAKKER_DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DISEASE_TRAKKER_DATABASE_PORT'] || '5432' %>
