name: Rails Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Install Bundler
        run: gem install bundler
      - name: Install Yarn
        run: npm install yarn
      - name: Run Yarn Install
        run: yarn install --ignore-engines
      - name: Run Bundle Install
        run: bundle install
      - name: Setup Test Database Configuration
        run: |
          cp config/github-ci/github-database.yml config/database.yml
          run: mysql -h 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -u root -p root -e 'CREATE DATABASE IF NOT EXISTS disease_trakker_test;'
      - name: Run Rake Test
        run: bundle exec rake test
        env:
          CI_SQL_PORT: ${{ job.services.mysql.ports['3306'] }}


